### ISSUE TITLE
Clean up Conda environment

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-NFcookiecutter#17]
This should save us a bit space:

https://github.com/SciLifeLab/Sarek/issues/551#issuecomment-376432593

(wil ldo that later..I think its a good idea to clean up the installers after the installation!)

**Comment by ewels** [comment]
Nice 👍

**Comment by maxulysse** [comment]
Definitively B-)
Marcel often has good ideas

**Comment by ewels** [comment]
I [just tested this](https://github.com/ewels/NGI-RNAseq/commit/56c22c4b38a65fdc314b91951c1d01f0507c0f37) on NGI-RNAseq as I had the repo open anyway, and the [container size](https://hub.docker.com/r/ewels/ngi-rnaseq/tags/) dropped from 2GB to 1GB (3.63GB &rarr; 2.89GB when uncompressed)

Super nice! 🎉

**Comment by maxulysse** [comment]
I like this virtuous circle!

**Comment by apeltzer** [comment]
Currently at a meeting in Basel - but I have 3.5h train back in the evening, so this is definitely going into cookiecutter!

**Comment by ewels** [comment]
It should be a two-second [copy and paste](https://github.com/ewels/NGI-RNAseq/commit/56c22c4b38a65fdc314b91951c1d01f0507c0f37)... 😉  _\* ..restrains fingers from keyboard... \*_

**Comment by ewels** [comment]
Sorry, that sounded kind of mean after writing! No rush :) And excellent find.. 👍
