### ISSUE TITLE
Add support for bioconda built containers

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-NFcookiecutter#3]
Write a docker build script that installs all dependencies using a bioconda env file. Then we can use bioconda, docker and singularity all from a single script which is super easy to maintain 🎉

**Comment by apeltzer** [comment]
This also related to https://github.com/nf-core/tools/issues/11 , where a basic example of this approach is shown. I'll update the example, test it and then provide feedback for everyone.

**Comment by sven1103** [comment]
I think having a Docker build template for bioconda is a killer feature. We also discussed this internally especially for what you call 'fat containers'. We thought it is more sustainable to contribute to bioconda with a recipe, than have just another container, nobody uses except ourselves.  

You all know this one: https://xkcd.com/927/ :)

**Comment by apeltzer** [comment]
See pull request #10

**Comment by ewels** [comment]
Ah crap, sorry @apeltzer - I'd forgotten that you already had a PR for this. Ah well, see also request #12 😉
