### ISSUE TITLE
Don't use executor local

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-NFcookiecutter#30]
Forcing `executor: local` for specific processes can break the pipeline for some systems (see https://github.com/nextflow-io/nextflow/issues/693#issuecomment-391792952).

Update this and all nf-core pipelines to remove that.

**Comment by alneberg** [comment]
So @ewels, am I right I am supposed to remove all occurrences of "executor: local"? Should it be replaced by something? Any corner cases?
