### ISSUE TITLE
Figure out how to handle singularity mount points for many users

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-NFcookiecutter#4]
One of the biggest problems that I can see with singularity images in pipelines designed to be used by everyone is bind points - mounting root directories within the container. The `ENABLE_OVERLAYS` option doesn't seem to be set for most people, so currently all root directory paths have to be added in the docker build script. This isn't exactly scaleable and we could do with a better solution.

Is there a better way to handle this?

**Comment by ewels** [comment]
Discussed on gitter [here](https://gitter.im/nextflow-io/nextflow?at=5a82c5c4e217167e2c7a6b31)

> @pditommaso
> first version of singularity overlay was disabled by default because it was buggy
> now it should be available by default if not disabled by sysadmins

So maybe everyone does now have overlays enabled and we don't need to worry about it after all. 🎉

**Comment by pditommaso** [comment]
If they don't, it's their problem :)

**Comment by ewels** [comment]
So a transcript of more internal discussion:

> I think this is mostly up to what you want to support for end targets. RHEL6 derivatives will typically not support overlays. But given that RHEL7 was released in 2014, I think it's fair to consider the group running on those systems a small and shrinking exception.
> Is it feasible in a sane fashion to check supplied if data paths exists withing the container name space and give a sensible message if not?

@pditommaso - what do you think? If using singularity, could core nextflow check that staged input files are readable and throw a nice informative error message if not? At the moment stuff just fails with the tool complaining that the file doesn't exist. This never fails to confuse people as they try to debug and see that the file clearly does exist. Or maybe I could just add in a command that checks the singularity config to ensure that `enable overlay = yes`. Or perhaps I should just stop worrying and let people figure stuff out themselves.

**Comment by pditommaso** [comment]
Um, not sure it's NF role to check if a file is readable. That would mean add an extra unnecessary overhead, in particular in the context of HPC cluster. I think NF separate things very clearly, allowing the troubleshoot of each task independently the remaining part of the pipeline. That's something that any user should be able to do.

**Comment by ewels** [comment]
Yeah, I was kind of coming to the same conclusion as I was typing but I figured I would see what you thought anyway 😀 I think I'll just ignore this problem for now 👍 

Thanks for the discussion!
