### ISSUE TITLE
Cookiecutter version should match the nf-core tools version

### ISSUE THREAD

**Issue by sven1103** [SciLifeLab/NGI-NFcookiecutter#43]
Idealy, to be consistent, a `nf-core tools` version should have a matching `cookiecutter` template version, so we can easily find corresponding pairs :) My suggestion is, that if they have the same version, the linting should pass.

**Comment by ewels** [comment]
> My suggestion is, that if they have the same version, the linting should pass.

Is the most common scenario not that tests are running on development code for both though?

**Comment by sven1103** [comment]
The problem is, if you have implemented a pipeline from a certain commit of the cookiecutter template, and the `nf-core tools` changes in the meantime, your linting will fail. But know that I am thinking about it again, for a release you have to make sure it passes the current tools version anyway. Maybe we can close this then.

**Comment by ewels** [comment]
👍
