### ISSUE TITLE
Speed up Conda Resolving

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-NFcookiecutter#45]
To my knowledge, conda package resolving should speed up significantly, when we specify the way packages are pulled by a corresponding prefix, e.g.:

`- conda-forge::jdk=1.X.Y`

is much faster than 
`- jdk=1.X.Y`

Maybe we should make this something that is automatically added to the `environment.yml` when a new repository is created to make users more aware of this?

**Comment by ewels** [comment]
I'd be curious to see how much of a difference this actually makes first.. 🤔

**Comment by maxulysse** [comment]
Yes, you're saying much faster, but how much faster?

**Comment by apeltzer** [comment]
I took making the Singularity container for the chipseq pipeline as an example:

Explicit paths:
```
real	22m35.586s
user	29m5.709s
sys	1m59.633s
``` 
Non explicit paths:
```
real	25m45.530s
user	31m45.949s
sys	2m36.789s
```

So its measurable, but not necessary in my opinion. Any thoughts on this?

**Comment by ewels** [comment]
Cool, thanks for checking! I think no need for now.
