### ISSUE TITLE
Documentation redundancy

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-NFcookiecutter#46]
The files `local.md` and `adding_your_own.md` have similar (if not identical) sections for Docker and Singularity - we should remove these in one location at least :-)

**Comment by apeltzer** [comment]
e.g. check out [adding_your_own.md](https://github.com/nf-core/cookiecutter/blob/master/%7B%7Bcookiecutter.pipeline_slug%7D%7D/docs/configuration/adding_your_own.md#software-requirements) and [local](https://github.com/nf-core/cookiecutter/blob/master/%7B%7Bcookiecutter.pipeline_slug%7D%7D/docs/configuration/local.md#-cookiecutterpipeline_name--local-configuration)

**Comment by ewels** [comment]
This issue was moved to nf-core/tools#97
