### ISSUE TITLE
AWSBatch Configuration

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-NFcookiecutter#48]
Hi!

I think we could have a generic AWSBatch configuration in cookiecutter. 

Did so for ICGC-featureCounts but we could use a similar way (open for ideas if thats not optimal in your opinion):

AWSBatch config:

https://github.com/nf-core/ICGC-featureCounts/blob/master/conf/awsbatch.config

Main Nextflow.config / setting some defaults:
https://github.com/nf-core/ICGC-featureCounts/blob/master/nextflow.config

And then allowing users to specify the required params /also using that in the summary if the proper profile is used:

https://github.com/nf-core/ICGC-featureCounts/blob/4929959b77d13169a8c96ef4abec3ff8b8af314e/main.nf#L138

I guess this could as well be extrapolated to other pipelines easily and could be in cookiecutter therefore!

I'd be happy to contribute that but would like to have some more feedback/ideas on this before moving on...

**Comment by maxulysse** [comment]
I would love to see that as well

**Comment by apeltzer** [comment]
cross linking an example here, which even checks for the params in the `main.nf` https://github.com/nf-core/rnaseq/pull/42

**Comment by ewels** [comment]
This issue was moved to nf-core/tools#99
