### ISSUE TITLE
Build MIT license from template

### ISSUE THREAD

**Issue by sven1103** [SciLifeLab/NGI-NFcookiecutter#5]
Currently, we enforce the provision of an MIT license, but the cookiecutter template does not create one by default.

**Comment by ewels** [comment]
Yes, I removed this after having questions from small companies who wanted to use the template and thought that they couldn't as it generated the MIT licence. I intended to add this back with a cookiecutter question / logic, but it wasn't trivial and so I skipped it.

I think now that it's fine to add this file in and just add a bit to the readme about it, saying that it's an example template file and can be removed.

**Comment by sven1103** [comment]
Nooo, i just wanted to submit a PR

**Comment by sven1103** [comment]
I think, in the context of nf-core, it makes sense, as we made MIT as requirement. And lint test should pass for the template IMO. People can still remove the LICENSE at their own requirement, risk, ...

**Comment by sven1103** [comment]
:smile:

**Comment by ewels** [comment]
I’m certainly happy for this now that this repo is part of nf-core.. :)

Previous stuff was when it was stand-alone and no policies attached..
