### ISSUE TITLE
Sort out better release tagging for singularity

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-NFcookiecutter#53]
Docker hub works nicely with automated builds based on GitHub releases which are tagged with the same name.

Singularity hub doesn't support the same method and instead has nasty filename based tagging support. However, there is a [very nice CLI](https://singularityhub.github.io/sregistry-cli/) that interacts with the API.

We should be able to use this CLI to automatically build and tag singularity hub containers when GitHub releases are prepared, using Travis CI.

**Comment by apeltzer** [comment]
We should discuss this too - maybe tomorrow?

**Comment by ewels** [comment]
This issue was moved to nf-core/tools#102
